# Generated by Django 4.0.3 on 2022-04-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='posts', through='news.PostCategory', to='news.category'),
        ),
    ]
